# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableAafAaf }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aaf
  name: aaf
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.aafReplicas }}
  selector:
    matchLabels:
      app: aaf
  template:
    metadata:
      labels:
        app: aaf
      name: aaf
    spec:
      initContainers:
      - command:
        - /root/ready.py
        args:
        - --container-name
        - aaf-cs
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.image.readiness }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: aaf-readiness
      containers:
      - env:
        - name: CASSANDRA_CLUSTER
          value: cassandra_container
        image: {{ .Values.image.aafImage }}:{{ .Values.image.aafVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        volumeMounts:
        - mountPath: /data
          name: aaf-data
        name: aaf
        readinessProbe:
          tcpSocket:
            port: 8101
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: aaf-data
          configMap:
            name: aaf-data-configmap
      imagePullSecrets:
      - name: {{ .Values.nsPrefix }}-docker-registry-key
#{{ end }}
